#pragma once

namespace global_domination
{
	enum ControlID
	{
		UNDEFINED_CONTROL_ID,

		FINANCES_BALANCE_LABEL,
		INBOX_LIST,
		INBOX_TITLE_LABEL,
		MAIN_MENU,
		NATION_SELECTION_MENU,
		NATION_SELECTION_GDP_LABEL,
		NATION_SELECTION_GDP_PER_CAPITA_LABEL,
		NATION_SELECTION_POPULATION_LABEL,
		NATION_SELECTION_PROMPT_LABEL,
		SELECTED_MESSAGE_TEXT_LABEL,
		SELECTED_MESSAGE_TITLE_LABEL,
		TOOLBAR_MENU_HOME,
		TOOLBAR_MENU_SETTINGS
	};
}
