#pragma once

namespace global_domination
{
	enum ControlID
	{
		UNDEFINED_CONTROL_ID,

		FINANCES_DATA_GRID,
		FINANCES_PLOT,
		INBOX_LIST,
		INBOX_TITLE_LABEL,
		MAIN_MENU,
		NATION_SELECTION_MENU,
		NATION_SELECTION_GDP_LABEL,
		NATION_SELECTION_GDP_PER_CAPITA_LABEL,
		NATION_SELECTION_POPULATION_LABEL,
		NATION_SELECTION_PROMPT_LABEL,
		SELECTED_MESSAGE_TEXT_LABEL,
		SELECTED_MESSAGE_TITLE_LABEL,
		TOOLBAR_DATE_LABEL,
		TOOLBAR_MENU_HOME,
		TOOLBAR_MENU_SETTINGS,
		TRADE_DEAL_LIST,
		TRADE_DEALS_PANE,
		TRADE_OFFERS_LIST,
		TRADE_OFFERS_PANE,
		TRADE_RESOURCE_LIST,
		TRADEVIEW_ACCEPTOFFER_BUTTON,
		TRADEVIEW_CANCELDEAL_BUTTON,
		TRADEVIEW_DECLINEOFFER_BUTTON,
		TRADEVIEW_DEAL_EXPIRYDATE_LABEL,
		TRADEVIEW_DEAL_RESOURCE_LABEL,
		TRADEVIEW_DEAL_TOTALVALUE_LABEL,
		TRADEVIEW_DEAL_VALUEPERANNUM_LABEL,
		TRADEVIEW_RESOURCES_LABEL,
		TRADEVIEW_TRADEDEALS_BUTTON,
		TRADEVIEW_TRADEOFFERS_BUTTON
	};
}
